BinaryStudioAcademy/bsa-2024-outreachvids

frontend/src/bundles/common/components/button/button.tsx
frontend/src/bundles/common/components/components.ts
frontend/src/bundles/users/components/components.ts
frontend/src/bundles/users/components/user-card/user-card.tsx
frontend/src/framework/theme/styles/colors.styles.ts
frontend/src/framework/theme/styles/components.styles.ts

This PR adds the User card component. In parent container it spans the whole width.

OV-12: User card

---

frontend/src/bundles/common/components/components.ts
frontend/src/framework/theme/styles/colors.styles.ts
frontend/src/framework/theme/styles/components.styles.ts

I added the colors and typography to be used in the project, and also defined the variants for headings and text.

OV-10: + colors and typography

---

frontend/src/bundles/auth/components/common/password-input/password-input.tsx
frontend/src/bundles/auth/components/sign-in-form/sign-in-form.tsx
frontend/src/bundles/auth/components/sign-up-form/sign-up-form.tsx
frontend/src/bundles/common/components/input/input.tsx

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/71
Sign-In:
Sign-Up:

OV-71: Add asterisk to required auth fields

---

README.md

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/88
This PR adds ERD.

OV-88: Update readme with erd

---

backend/src/bundles/auth/auth.controller.ts
backend/src/bundles/users/user.controller.ts

Depends on [PR for OV-59](https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/pull/69#pullrequestreview-2266745276).
Fixed existing swagger docs for auth controller and user controller.
Response from /sign-in
Request body for /sign-up
Response for /sign-up
Response for GET /users

OV-77: fix swagger docs

---

backend/src/bundles/auth/auth.controller.ts
backend/src/bundles/users/user.controller.ts
backend/src/bundles/videos/video.controller.ts
backend/src/common/constants/white-routes.constants.ts
backend/src/common/plugins/auth/types/route.type.ts
frontend/src/bundles/auth/auth-api.ts
frontend/src/bundles/users/users-api.ts
frontend/src/framework/http/enums/enums.ts
frontend/src/framework/http/http.ts
frontend/src/framework/http/types/types.ts
shared/src/framework/http/enums/http-method.enum.ts
shared/src/framework/http/types/http-method.type.ts

This task is to solve this task: https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/100
Images that shows all is runing as expected

OV-100: Update HttpMethod usage

---

frontend/src/bundles/common/components/header/header.tsx

This PR fixes the zIndex in the header component.

OV-108: fix header

---

frontend/src/bundles/auth/store/actions.ts
frontend/src/bundles/auth/store/auth.ts
frontend/src/bundles/auth/store/slice.ts
frontend/src/bundles/common/components/sidebar/sidebar.tsx

Handle user logout, remove user token from browser local storage, remove user from store, and redirects to sign in

OV-128: Handle-logout

---

.github/workflows/cd.yml
backend/src/common/constants/white-routes.constants.ts
backend/src/common/plugins/auth/auth-jwt.plugin.ts
backend/src/common/plugins/auth/constants/constants.ts
backend/src/common/plugins/auth/constants/served-page-path.constant.ts

OV-159: Add static path white route

---

backend/src/bundles/chat/chat.controller.ts
backend/src/bundles/users/user.controller.ts
backend/src/bundles/videos/video.controller.ts
backend/src/common/server-application/base-server-app-api.ts

This PR add bearer token authentication functionality to swagger and correct endpoints URL's

OV-170: Add Swagger base URL and bearer auth

---

frontend/src/bundles/common/components/sidebar/sidebar.tsx
frontend/src/bundles/users/components/user-card/components/user-avatar.tsx
frontend/src/bundles/users/components/user-card/helpers/get-initials.helper.ts
frontend/src/bundles/users/components/user-card/helpers/helpers.ts
frontend/src/bundles/users/components/user-card/user-card.tsx

Get fullName from store and add it to user card, then get initials from it and add it to user avatar. If no name is provided placeholder is rendered

OV-133: Add-user-name

---

frontend/src/bundles/common/components/components-provider/components-provider.tsx
frontend/src/bundles/common/components/components.ts
frontend/src/index.tsx

Move ChakraProvider to a separate component and add a custom CacheProvider. Now chakra styles appear at the top of the head block.

OV-180: + set lower priority to chakra styles

---

frontend/src/bundles/auth/pages/auth.tsx

OV-189: Add loader to auth page

---

frontend/src/bundles/common/components/protected-route/protected-route.tsx

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/220

OV-220: Wrap loader in overlay

---

frontend/src/app/app.tsx
frontend/src/bundles/auth/pages/auth.tsx
frontend/src/bundles/common/components/protected-route/protected-route.tsx

OV-187: Fix sign in redirection after logout

---

frontend/src/bundles/common/components/overlay/overlay.tsx

OV-216: Change overlay background color to blue

---

frontend/src/bundles/common/components/video-modal/components/video-modal-content/components/video-preview/video-preview.tsx
frontend/src/bundles/studio/store/slice.ts

On buttons click, the studio page opens and the video size is stored to the studio slice.

OV-219: Open studio page

---

frontend/src/bundles/studio/pages/studio.tsx

Changed download button to submit and it redirects to root
https://github.com/user-attachments/assets/b10c27ea-55b7-4e35-8a06-9d308506f06f

OV-206:  Change download button to submit button on studio

---

frontend/src/bundles/common/components/video-modal/components/video-modal-content/components/tab/tab.tsx

Issue described in comments for task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/73

OV-73: Fix video modal icon size

---

backend/src/bundles/users/user.entity.ts
backend/src/bundles/users/user.service.ts

This PR is for this task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/215
It was apply on the backend, as there is where the validations and store of the data are made

OV-215:  Adjust Email As Case Insensitive In Auth

---

backend/src/common/plugins/auth/auth-jwt.plugin.ts
backend/src/common/plugins/auth/enums/error-message.enum.ts
backend/src/common/server-application/base-server-app.ts

Reverts BinaryStudioAcademy/bsa-2024-outreachvids#248

OV-221: Adjust Backend Respond when Endpoint is not found REVERT

---

frontend/src/bundles/studio/components/timeline/timeaxis/styles.module.css
frontend/src/bundles/studio/components/timeline/timecursor/styles.module.css
frontend/src/bundles/studio/components/video-menu/components/menu-content/avatars-content/avatars-content.tsx

This PR is for this task https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/262
https://github.com/user-attachments/assets/0ae6cd45-f47b-49aa-a71d-7149ff259d43

OV-262: Dont Reload Avatars On Each Modal Open

---

frontend/src/bundles/studio/components/video/video.tsx

OV-268: fix player

---

frontend/src/bundles/common/components/logo/logo.tsx

OV-281: Fix misaligned logo

---

frontend/src/bundles/common/components/components.ts
frontend/src/bundles/studio/pages/studio.tsx
frontend/src/bundles/studio/pages/styles.module.css
frontend/src/bundles/studio/store/slice.ts

In this pr:
- Added input for video name
- Store video name in the store
On hover:
On focus:

OV-291: Add video name

---

frontend/src/bundles/studio/components/video-menu/components/menu-body/styles.module.css

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/277

OV-277: Fix scripts layout

---

frontend/src/bundles/home/components/main-content/main-content.tsx
frontend/src/bundles/home/components/main-content/styles.module.css

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/282

OV-282: Fix video-section height

---

backend/src/common/services/file/file.service.ts

Related issue - https://github.com/BinaryStudioAcademy/bsa-2024-outreachvids/issues/252

OV-252: Add delete method to AWS fileService

---

frontend/src/bundles/common/components/player/player.tsx
frontend/src/bundles/studio/components/video/styles.module.css

Changed background color to grey as seen in Figma

OV-313: Change player background to grey

---

frontend/src/bundles/studio/components/audio-player/audio-player.tsx
frontend/src/bundles/studio/components/video-menu/components/menu-content/script-content/components/script.tsx
frontend/src/bundles/studio/components/video-menu/components/menu-content/script-content/components/voices-modal/components/voice-card.tsx
frontend/src/bundles/studio/components/video-menu/components/menu-content/script-content/components/voices-modal/components/voices-modal-content.tsx
frontend/src/bundles/studio/components/video-menu/components/menu-content/script-content/script-content.tsx
frontend/src/bundles/studio/pages/studio.tsx
frontend/src/bundles/studio/store/actions.ts
frontend/src/bundles/studio/store/slice.ts
frontend/src/bundles/studio/store/studio.ts
frontend/src/bundles/studio/types/script.type.ts

Send request to tts for voices modal. Move player to studio page, connect with store.

OV-321: Send request to tts for voices modal

---

frontend/src/bundles/common/components/player/styles/landscape.style.ts
frontend/src/bundles/common/components/player/styles/portrait.style.ts

OV-328: Make bigger video holder
